services:
  qwen3-reranker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: qwen3-reranker:prod
    container_name: qwen3-reranker-prod
    restart: unless-stopped
    ports:
      - "8004:8000"
    volumes:
      - ./hf_cache:/app/cache
      - ./logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - config.env
    environment:
      - TZ=America/Sao_Paulo
      # Uvicorn optimizations
      - UVICORN_WORKERS=1
      - UVICORN_LOOP=uvloop
      - UVICORN_HTTP=httptools
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["1"]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
