services:
  qwen3-reranker:
    build:
      context: .
    image: qwen3-reranker:latest
    container_name: qwen3-reranker
    restart: always
    ports:
      - 8004:8000
    volumes:
      - ./main.py:/app/main.py
      - ./hf_cache:/app/cache
      - ./logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MODEL_NAME=Qwen/Qwen3-Reranker-0.6B
      - ENABLE_LOGGING=true
      - LOG_FILE_PATH=/app/logs/requests.log
      - LOG_METHOD=async
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              #count: all
              device_ids: ["1"]
