services:
  qwen3-reranker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 10001
    image: qwen3-reranker:production
    container_name: qwen3-reranker-prod
    restart: unless-stopped
    ports:
      - "8004:8000"
    volumes:
      # Persistent cache for model downloads
      - ./hf_cache:/app/cache
      # Logs directory
      - ./logs:/app/logs
      # Timezone configuration
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      # Production optimizations
      - UVICORN_WORKERS=1
      - UVICORN_LOOP=uvloop
      - UVICORN_HTTP=httptools
      # GPU memory optimization
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
        compress: "true"
    # Security hardening
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=1G
      - /var/tmp:noexec,nosuid,size=500M
